### ISSUE TITLE
@hapi/boom:7.4.5+ breaks central-services-error-handling

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1006]
**Summary**:
When upgrading dependencies in the `account-lookup-service`, I noticed that newer versions of `@hapi/boom` were throwing an error when trying to convert a `FSPIOPError` object into a hapi response object. This was happening when throwing a `FSPIOPError` in a hapi handler function, e.g.

```js
put: function (request, h) {
    throw ErrorHandler.Factory.createFSPIOPError(ErrorHandler.Enums.FSPIOPErrorCodes.NOT_IMPLEMENTED)
},
```

The stack trace is as follows:

```
TypeError: Cannot read property 'configurable' of undefined

      at Object.<anonymous>.internals.initialize (node_modules/@hapi/hapi/node_modules/@hapi/boom/lib/index.js:394:27)
      at Function.boomify (node_modules/@hapi/hapi/node_modules/@hapi/boom/lib/index.js:117:30)
      at Object.<anonymous>.module.exports.internals.Manager.execute (node_modules/@hapi/hapi/lib/toolkit.js:55:33)
      at Object.<anonymous>.internals.handler (node_modules/@hapi/hapi/lib/handler.js:46:48)
      at Object.<anonymous>.exports.execute (node_modules/@hapi/hapi/lib/handler.js:31:36)
      at Request._lifecycle (node_modules/@hapi/hapi/lib/request.js:312:68)
```

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
The error should be converted as with the previous versions of `@hapi/boom`

**Steps to Reproduce**
  1. Go to ALS
  2. Upgrade `@hapi/boom` to version 7.4.5 or above
  3. run the integration tests, and observe above error

**Specifications**
  - Component (if known): `central-services-error-handling`, `account-lookup-service`
  - Version: 
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @lewisdaly @rmothilal 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by lewisdaly** [comment]
False alarm.

`createFSPIOPError` was being called incorrectly, and was missing the `message` parameter.

When I changed from:
```js
throw ErrorHandler.Factory.createFSPIOPError(ErrorHandler.Enums.FSPIOPErrorCodes.NOT_IMPLEMENTED)
```

to:
```js
throw ErrorHandler.Factory.createFSPIOPError(ErrorHandler.Enums.FSPIOPErrorCodes.NOT_IMPLEMENTED, 'Not Implemented')
```

This issue went away.
