### ISSUE TITLE
ErrorInformation includes extensionList with key and value

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1010]
**Summary**:
It was decided to remove error information such as extensionList and extension, Key and Value. 

**Severity**:
(Medium)

**Priority**:
(Critical)

**Expected Behavior**
No extensionList
eg:
{
    "errorInformation": {
        "errorCode": "3101",
        "errorDescription": "Malformed syntax - Transfer Id must be in a valid GUID format."
    }
}

**Steps to Reproduce**
  1. PUT /Transfers - missing ID
 2. PUT /Quotes - missing ID

curl -X PUT \
  http://dev1-ml-api-adapter.mojaloop.live/transfers \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer {{BEARER_TOKEN}}' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Content-Type: application/vnd.interoperability.transfers+json;version=1' \
  -H 'Date: Tue, 08 Oct 2019 11:19:41 GMT' \
  -H 'FSPIOP-Destination: payeefsp' \
  -H 'FSPIOP-Source: noresponsepayeefsp' \
  -H 'Host: dev1-ml-api-adapter.mojaloop.live' \
  -H 'Postman-Token: fc0e6521-5cb1-444f-b926-1b38378d74cd,1079b109-16da-4e5b-9906-3e3479a82b9e' \
  -H 'User-Agent: PostmanRuntime/7.17.1' \
  -H 'cache-control: no-cache'

**Response:**
{
    "errorInformation": {
        "errorCode": "3002",
        "errorDescription": "Unknown URI - Not Found",
        "extensionList": {
            "extension": [
                {
                    "key": "cause",
                    "value": "Error: Not Found\n    at internals.notFound (/opt/ml-api-adapter/node_modules/@hapi/hapi/lib/core.js:632:16)\n    at module.exports.internals.Manager.execute (/opt/ml-api-adapter/node_modules/@hapi/hapi/lib/toolkit.js:41:33)\n    at Object.internals.handler (/opt/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:46:48)\n    at exports.execute (/opt/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:31:36)\n    at Request._lifecycle (/opt/ml-api-adapter/node_modules/@hapi/hapi/lib/request.js:312:68)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
                }
            ]
        }
    }
}

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:Murthy/@amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by rmothilal** [comment]
@gibaros's latest change to ErrorHandling library with regards to story #990

**Comment by elnyry** [comment]
> @gibaros's latest change to ErrorHandling library with regards to story #990 should fix this issue. will await release and retest

Updated the story to include 'Validate tasks' instead of 'fix' following Rajiv's comment above.

Moving this back to backlog for validation

**Comment by ggrg** [comment]
This has been now verified for ml-api-adapter, central-ledger and central-settlement, but all services need to use the latest version. As there's currently a PR https://github.com/mojaloop/central-services-error-handling/pull/84 for #981 under review, I'll postpone resolving this until v8.3.0 is out and then upgrade all in the list.
