### ISSUE TITLE
Error with config in CEP - v8.1.0 helm, v8.2.0 CEP

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#1049]
**Summary**:
Error: Configuration property "AMOUNT.SCALE" is not defined in Config for CEP

**Severity**:
Medium

**Priority**:
Medium

**Pull Requests**:
- [x] https://github.com/mojaloop/helm/pull/221
- [x] https://github.com/mojaloop/central-event-processor/pull/88

**Expected Behavior**
- AMOUNT.SCALE is part of config in CEP and there's no issue with running the service

**Steps to Reproduce**
  1. Deploy ML default
  2. Review CEP logs

Logs:
```
2019-11-05T17:23:16.615Z - info: storeCurrentPositionForSettlementChange exit with error: Error: Configuration property "AMOUNT.SCALE" is not defined
2019-11-05T17:23:16.656Z - info: getParticipantEndpointsFromResponseObservable failed with error: {"message":"Configuration property \"AMOUNT.SCALE\" is not defined","apiErrorCode":{"code":"2001","message":"Internal server error","name":"INTERNAL_SERVER_ERROR","type":{"regex":"^20[0-9]{2}$","description":"Generic Server Error","name":"GENERIC_SERVER_ERROR"}},"cause":"'Error: Configuration property \"AMOUNT.SCALE\" is not defined\\n    at Config.get (/opt/central-event-processor/node_modules/config/lib/config.js:182:11)\\n    at storeCurrentPositionForSettlementChange (/opt/central-event-processor/src/observables/centralLedgerAPI.js:110:87)\\n    at Observable.Rx.Observable.create [as _subscribe] (/opt/central-event-processor/src/observables/centralLedgerAPI.js:144:9)\\n    at Observable._trySubscribe (/opt/central-event-processor/node_modules/rxjs/internal/Observable.js:44:25)\\n    at Observable.subscribe (/opt/central-event-processor/node_modules/rxjs/internal/Observable.js:30:22)\\n    at Object.subscribeToResult (/opt/central-event-processor/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)\\n    at MergeMapSubscriber._innerSub (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:82:29)\\n    at MergeMapSubscriber._tryNext (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:76:14)\\n    at MergeMapSubscriber._next (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:59:18)\\n    at MergeMapSubscriber.Subscriber.next (/opt/central-event-processor/node_modules/rxjs/internal/Subscriber.js:66:18)\\n    at FilterSubscriber._next (/opt/central-event-processor/node_modules/rxjs/internal/operators/filter.js:52:30)\\n    at FilterSubscriber.Subscriber.next (/opt/central-event-processor/node_modules/rxjs/internal/Subscriber.js:66:18)\\n    at Consumer.consumer.on (/opt/central-event-processor/src/setup.js:69:16)\\n    at Consumer.emit (events.js:194:15)\\n    at KafkaConsumer._consumer.on.message (/opt/central-event-processor/node_modules/@mojaloop/central-services-stream/src/kafka/consumer.js:318:15)\\n    at KafkaConsumer.emit (events.js:189:13)\\n    at /opt/central-event-processor/node_modules/node-rdkafka/lib/kafka-consumer.js:456:12'"}
{ FSPIOPError: Configuration property "AMOUNT.SCALE" is not defined
    at createFSPIOPError (/opt/central-event-processor/node_modules/@mojaloop/central-services-error-handling/src/factory.js:201:12)
    at Object.reformatFSPIOPError (/opt/central-event-processor/node_modules/@mojaloop/central-services-error-handling/src/factory.js:288:12)
    at storeCurrentPositionForSettlementChange (/opt/central-event-processor/src/observables/centralLedgerAPI.js:128:32)
    at Observable.Rx.Observable.create [as _subscribe] (/opt/central-event-processor/src/observables/centralLedgerAPI.js:144:9)
    at Observable._trySubscribe (/opt/central-event-processor/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/opt/central-event-processor/node_modules/rxjs/internal/Observable.js:30:22)
    at Object.subscribeToResult (/opt/central-event-processor/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)
    at MergeMapSubscriber._innerSub (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
    at MergeMapSubscriber._next (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/opt/central-event-processor/node_modules/rxjs/internal/Subscriber.js:66:18)
    at FilterSubscriber._next (/opt/central-event-processor/node_modules/rxjs/internal/operators/filter.js:52:30)
    at FilterSubscriber.Subscriber.next (/opt/central-event-processor/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Consumer.consumer.on (/opt/central-event-processor/src/setup.js:69:16)
    at Consumer.emit (events.js:194:15)
    at KafkaConsumer._consumer.on.message (/opt/central-event-processor/node_modules/@mojaloop/central-services-stream/src/kafka/consumer.js:318:15)
    at KafkaConsumer.emit (events.js:189:13)
    at /opt/central-event-processor/node_modules/node-rdkafka/lib/kafka-consumer.js:456:12
Error: Configuration property "AMOUNT.SCALE" is not defined
    at Config.get (/opt/central-event-processor/node_modules/config/lib/config.js:182:11)
    at storeCurrentPositionForSettlementChange (/opt/central-event-processor/src/observables/centralLedgerAPI.js:110:87)
    at Observable.Rx.Observable.create [as _subscribe] (/opt/central-event-processor/src/observables/centralLedgerAPI.js:144:9)
    at Observable._trySubscribe (/opt/central-event-processor/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/opt/central-event-processor/node_modules/rxjs/internal/Observable.js:30:22)
    at Object.subscribeToResult (/opt/central-event-processor/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)
    at MergeMapSubscriber._innerSub (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
    at MergeMapSubscriber._next (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/opt/central-event-processor/node_modules/rxjs/internal/Subscriber.js:66:18)
    at FilterSubscriber._next (/opt/central-event-processor/node_modules/rxjs/internal/operators/filter.js:52:30)
    at FilterSubscriber.Subscriber.next (/opt/central-event-processor/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Consumer.consumer.on (/opt/central-event-processor/src/setup.js:69:16)
    at Consumer.emit (events.js:194:15)
    at KafkaConsumer._consumer.on.message (/opt/central-event-processor/node_modules/@mojaloop/central-services-stream/src/kafka/consumer.js:318:15)
    at KafkaConsumer.emit (events.js:189:13)
    at /opt/central-event-processor/node_modules/node-rdkafka/lib/kafka-consumer.js:456:12
  name: 'FSPIOPError',
  cause:
   'Error: Configuration property "AMOUNT.SCALE" is not defined\n    at Config.get (/opt/central-event-processor/node_modules/config/lib/config.js:182:11)\n    at storeCurrentPositionForSettlementChange (/opt/central-event-processor/src/observables/centralLedgerAPI.js:110:87)\n    at Observable.Rx.Observable.create [as _subscribe] (/opt/central-event-processor/src/observables/centralLedgerAPI.js:144:9)\n    at Observable._trySubscribe (/opt/central-event-processor/node_modules/rxjs/internal/Observable.js:44:25)\n    at Observable.subscribe (/opt/central-event-processor/node_modules/rxjs/internal/Observable.js:30:22)\n    at Object.subscribeToResult (/opt/central-event-processor/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)\n    at MergeMapSubscriber._innerSub (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:82:29)\n    at MergeMapSubscriber._tryNext (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:76:14)\n    at MergeMapSubscriber._next (/opt/central-event-processor/node_modules/rxjs/internal/operators/mergeMap.js:59:18)\n    at MergeMapSubscriber.Subscriber.next (/opt/central-event-processor/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at FilterSubscriber._next (/opt/central-event-processor/node_modules/rxjs/internal/operators/filter.js:52:30)\n    at FilterSubscriber.Subscriber.next (/opt/central-event-processor/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at Consumer.consumer.on (/opt/central-event-processor/src/setup.js:69:16)\n    at Consumer.emit (events.js:194:15)\n    at KafkaConsumer._consumer.on.message (/opt/central-event-processor/node_modules/@mojaloop/central-services-stream/src/kafka/consumer.js:318:15)\n    at KafkaConsumer.emit (events.js:189:13)\n    at /opt/central-event-processor/node_modules/node-rdkafka/lib/kafka-consumer.js:456:12',
  replyTo: undefined,
  apiErrorCode:
   { code: '2001',
     message: 'Internal server error',
     name: 'INTERNAL_SERVER_ERROR',
     type:
      { regex: '^20[0-9]{2}$',
        description: 'Generic Server Error',
        name: 'GENERIC_SERVER_ERROR' } },
  httpStatusCode: undefined,
  extensions: undefined,
  useMessageAsDescription: false }

```

**Specifications**
  - Component (if known): central services
  - Version: v8.1.0 Helm, v8.2.0 CEP
  - Platform: AWS
  - Subsystem: central-event-processor
  - Type of testing: sanity testing
  - Bug found/raised by: @dgethings , Oscar Cobar, @elnyry 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by ggrg** [comment]
Leaving this in Review/QA until confirmed

**Comment by elnyry** [comment]
We have a release of CEP v8.4.0 with this update. Will re-open this in case the issue persists (with Helm v8.3.0)
