### ISSUE TITLE
POST /quotes for inactive participant sends 500 instead of 202 statuscode

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1181]
**Summary**:
POST /quotes for inactive participant sends 500 instead of 202 statuscode

![image](https://user-images.githubusercontent.com/53434415/72928876-aac5f700-3d50-11ea-8e52-a273c1842b0d.png)

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
202 response code for inactive participant id.

**Steps to Reproduce**
1. Make participant fsp id "payerfsp" as inactive.
```
curl --location --request PUT 'http://dev2-central-ledger.mojaloop.live/participants/payerfsp' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{BEARER_TOKEN}}' \
--data-raw '{
  "isActive": false
}'
```
2. now send the Post /quotes with below curl
```
curl --location --request POST 'http://dev2-quoting-service.mojaloop.live/quotes' \
--header 'Accept: application/vnd.interoperability.quotes+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
--header 'Date: Wed, 22 Jan 2020 19:47:07 GMT' \
--header 'FSPIOP-SOurce: payerfsp' \
--header 'FSPIOP-Destination: payeefsp' \
--data-raw '{
  "quoteId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
  "transactionId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "{{receiverMSISDN}}",
      "fspId": "payeefsp"
    }
  },
  "payer": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "27713803905",
      "fspId": "payerfsp"
    },
    "personalInfo": {
      "complexName": {
        "firstName": "Mats",
        "lastName": "Hagman"
      },
      "dateOfBirth": "1983-10-25"
    }
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "hej"
}'
```

Log
```
2020-01-22T19:39:54Z, (1579721994595:d2-880-01-quoting-service-5f84f4cccc-xtdpp:17:k5pnaoxz:10136) [response,api,quotes,sampled] http://0.0.0.0:3002: post /quotes {} 500 (41ms)
2020-01-22T19:47:07Z, [log,info] data: got a POST /quotes request: { quoteId: '249d49c9-c804-4d0b-801d-663edc6dbae2',
transactionId: '249d49c9-c804-4d0b-801d-663edc6dbae2',
payee:
{ partyIdInfo:
{ partyIdType: 'MSISDN',
partyIdentifier: '{{receiverMSISDN}}',
fspId: 'payeefsp' } },
payer:
{ partyIdInfo:
{ partyIdType: 'MSISDN',
partyIdentifier: '27713803905',
fspId: 'payerfsp' },
personalInfo: { complexName: [Object], dateOfBirth: '1983-10-25' } },
amountType: 'SEND',
amount: { amount: '100', currency: 'USD' },
transactionType:
{ scenario: 'TRANSFER',
initiator: 'PAYER',
initiatorType: 'CONSUMER' },
note: 'hej' }
2020-01-22T19:47:07.744Z - audit: {
"event": {
"id": "92f1feed-4e8c-4e0c-ba0a-652981b6b083",
"type": "audit",
"action": "start",
"createdAt": "2020-01-22T19:47:07.743Z",
"state": {
"status": "success"
}
},
"trace": {
"startTimestamp": "2020-01-22T19:47:07.741Z",
"service": "qs_quote_request",
"traceId": "b5b5de5d7a71f17c17b5706fb4adb967",
"spanId": "d712fcd34a5aafa6",
"tags": {
"tracestate": "mojaloop=d712fcd34a5aafa6",
"transactionType": "quote",
"transactionAction": "prepare",
"transactionId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
"quoteId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
"source": "payerfsp",
"destination": "payeefsp",
"payeeFsp": "payeefsp",
"payerFsp": "payerfsp"
}
}
}
2020-01-22T19:47:07.749Z - error: {
"event": {
"id": "255b9442-4ece-4055-84ad-429c44bedd9d",
"type": "log",
"action": "error",
"createdAt": "2020-01-22T19:47:07.749Z",
"state": {
"status": "failed",
"code": "3202",
"description": "Payer FSP ID not found"
}
},
"trace": {
"startTimestamp": "2020-01-22T19:47:07.741Z",
"service": "qs_quote_request",
"traceId": "b5b5de5d7a71f17c17b5706fb4adb967",
"spanId": "d712fcd34a5aafa6",
"tags": {
"tracestate": "mojaloop=d712fcd34a5aafa6",
"transactionType": "quote",
"transactionAction": "prepare",
"transactionId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
"quoteId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
"source": "payerfsp",
"destination": "payeefsp",
"payeeFsp": "payeefsp",
"payerFsp": "payerfsp"
}
}
}
2020-01-22T19:47:07Z, [log,error] data: ERROR - POST /quotes: FSPIOPError: Unsupported participant 'payerfsp'
at Object.createFSPIOPError (/opt/quoting-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:198:12)
at CachedDatabase.getParticipant (/opt/quoting-service/src/data/database.js:358:38)
2020-01-22T19:47:07.755Z - audit: {
"event": {
"id": "b868b3af-023a-4093-b403-2f9e846a9fac",
"type": "audit",
"action": "start",
"createdAt": "2020-01-22T19:47:07.755Z",
"state": {
"status": "success"
}
},
"trace": {
"startTimestamp": "2020-01-22T19:47:07.755Z",
"service": "qs_quote_sendErrorCallback",
"traceId": "b5b5de5d7a71f17c17b5706fb4adb967",
"spanId": "56b51891ba97aecb",
"parentSpanId": "d712fcd34a5aafa6",
"tags": {
"tracestate": "mojaloop=56b51891ba97aecb",
"transactionType": "quote",
"transactionAction": "prepare",
"transactionId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
"quoteId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
"source": "payerfsp",
"destination": "payeefsp",
"payeeFsp": "payeefsp",
"payerFsp": "payerfsp"
}
}
}
2020-01-22T19:47:07.759Z - audit: {
"event": {
"id": "d3f05f2d-698b-449c-be1b-66785b5e8bad",
"type": "audit",
"action": "egress",
"createdAt": "2020-01-22T19:47:07.759Z",
"state": {
"status": "success"
}
},
"trace": {
"startTimestamp": "2020-01-22T19:47:07.755Z",
"service": "qs_quote_sendErrorCallback",
"traceId": "b5b5de5d7a71f17c17b5706fb4adb967",
"spanId": "56b51891ba97aecb",
"parentSpanId": "d712fcd34a5aafa6",
"tags": {
"tracestate": "mojaloop=56b51891ba97aecb",
"transactionType": "quote",
"transactionAction": "prepare",
"transactionId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
"quoteId": "249d49c9-c804-4d0b-801d-663edc6dbae2",
"source": "payerfsp",
"destination": "payeefsp",
"payeeFsp": "payeefsp",
"payerFsp": "payerfsp"
}
}
}
2020-01-22T19:47:07Z, (1579722427741:d2-880-01-quoting-service-5f84f4cccc-xtdpp:17:k5pnaoxz:10137) [response,api,quotes,sampled] http://0.0.0.0:3002: post /quotes {} 500 (40ms)
```

**Specifications**
Component (if known): central-services
Version:v8.8.0
Platform: Dev 2, AWS
Subsystem:quoting service
Type of testing: Regression testing
Bug found/raised by:@amarmodus,

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by amarmodus** [comment]
<img width="1279" alt="Screenshot 2020-02-03 10 30 10" src="https://user-images.githubusercontent.com/53434415/73645931-3eac9280-4670-11ea-83b1-43cf57999df9.png">

**Comment by amarmodus** [comment]
verified in Dev2
