### ISSUE TITLE
Upgrade from previous version causes centralledger-service to crash on init container

### ISSUE THREAD

**Issue by Kalaston** [mojaloop/project#1255]
**Summary**:
Whenever an upgrade is made to Mojaloop 9.2.0, the centralledger-service will crash on the `run-migration` init container.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
An upgrade from Mojaloop version 8.8.0 to version 9.2.0 should be handled without the centralledger-service crashing.

**Steps to Reproduce**
  1.Create an empty helm app and add Mojaloop as a dependency in the `requirements.yaml` file with version 8.8.0.
  2. Install Mojaloop with: `helm install --debug --name=test .`
  3. Wait for services to be ready.
  4. Upgrade Mojaloop version in `requirementsl.yaml` to version 9.2.0
  5. Upgrade the release with: `helm upgrade --install --debug test .`
  6. Wait for the services to be ready and once the centralledger-service crash, log the `run-migration` container.
Output:
```
> @mojaloop/central-ledger@9.3.0 migrate /opt/central-ledger
> run-s migrate:latest seed:run


> @mojaloop/central-ledger@9.3.0 migrate:latest /opt/central-ledger
> knex $npm_package_config_knex migrate:latest

Working directory changed to /opt/central-ledger/config
Error: The migration directory is corrupt, the following files are missing: 400401_settlmentWindowStateChange-indexes.js
    at validateMigrationList (/opt/central-ledger/node_modules/knex/lib/migrate/Migrator.js:564:11)
    at /opt/central-ledger/node_modules/knex/lib/migrate/Migrator.js:68:11
    at tryCatcher (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/central-ledger/node_modules/knex/node_modules/bluebird/js/release/async.js:102:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mojaloop/central-ledger@9.3.0 migrate:latest: `knex $npm_package_config_knex migrate:latest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @mojaloop/central-ledger@9.3.0 migrate:latest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Specifications**
  - Component (if known): run-migration container inside central-ledger-service
  - Version: 9.2.0
  - Platform:
  - Subsystem:
  - Type of testing: Manual
  - Bug found/raised by: Aaron Reynoza

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by mdebarros** [comment]
Fixes for this issue:
- Central-Ledger: https://github.com/mojaloop/central-ledger/pull/644
- Helm: TBD

**Comment by elnyry** [comment]
Should be fixed with this: https://github.com/mojaloop/helm/releases/tag/v9.2.0

**Comment by elnyry** [comment]
Confirmed with @Kalaston that its now fixed. Thanks @mdebarros
