### ISSUE TITLE
Quotation service doesn't send PUT /quotes/{ID}/error to FSP

### ISSUE THREAD

**Issue by agalaguz** [mojaloop/project#1305]
**Summary**:
We were tryiing to reproduce the next negative scenario between Payer FSP, Mojaloop and Payee FSP:
1. Payer FSP sends `POST /quotes` to Mojaloop 
2. Mojaloop sends `POST /quotes` to Payee FSP
3. Payee FSP sends `PUT /quotes/{ID}/error` to Mojaloop
4. Mojaloop sends `PUT /quotes/{ID}/error` to Payer FSP

Unfortunately, step 4 did not happen due to [an error](https://prnt.sc/s6t9zk) in Quotation Service.

**Error**:
```
020-04-27T12:17:38Z, [log,error] data: ERROR - PUT /quotes/{id}/error: FSPIOPError: Factory function createFSPIOPError failed due to apiErrorCode being invalid - {"code":"5103","message":""}.
    at createFSPIOPError (/opt/quoting-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:200:11)
    at Object.createFSPIOPErrorFromErrorInformation [as CreateFSPIOPErrorFromErrorInformation] (/opt/quoting-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:302:10)
    at QuotesModel.handleQuoteError (/opt/quoting-service/src/model/quotes.js:708:40)
    at QuotesByIdAndError (/opt/quoting-service/src/handlers/quotes/{id}/error.js:77:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports.internals.Manager.execute (/opt/quoting-service/node_modules/@hapi/hapi/lib/toolkit.js:45:28)
    at async Object.internals.handler (/opt/quoting-service/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at async exports.execute (/opt/quoting-service/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at async Request._lifecycle (/opt/quoting-service/node_modules/@hapi/hapi/lib/request.js:312:32)
    at async Request._execute (/opt/quoting-service/node_modules/@hapi/hapi/lib/request.js:221:9)
2020-04-27T12:17:38Z, (1587989858123:mj9-quoting-service-d46888699-jzbbk:24:k9cl2wgv:10039) [response,api,quotes,sampled] http://0.0.0.0:3002: put /quotes/898a9616-73fa-448d-88ab-ec48ac0d8c8a/error {} 200 (10ms)
2020-04-27T12:17:38Z, [log,info] data: POST quote request succeeded and returned: {}
2020-04-27T12:17:37Z, (1587989857724:mj9-quoting-service-d46888699-jzbbk:24:k9cl2wgv:10038) [response,api,quotes,sampled] http://0.0.0.0:3002: post /quotes {} 202 (1062ms) 
```

**Expected Behavior**
Mojaloop sends `PUT /quotes/{ID}/error` to Payer FSP after receiving it from `PUT /quotes/{ID}/error` from Payee FSP.

**Steps to Reproduce**
Send PUT /quotes/{ID}/error to Mojaloop.
Body data:
```
{
   "errorInformation": {
   "errorCode": "5103",
   "errorDescription": ""
   }
} 
```

**Specifications**
Helm release: https://github.com/mojaloop/helm/tree/release/v9.2.0

**Notes**:
Not sure if it is important, but we have set a single Participant endpoint for Quotes in Moja for both FSPs.
```
    "type": "FSPIOP_CALLBACK_URL_QUOTES",
    "value": "{fsp_url}"
```
And it works fine with POST and PUT messages. 

Kind regards,

**Comment by elnyry** [comment]
@agalaguz , I'd like to encourage you to use the 'bug' template from here. Regarding the issue, we'll triage it today and attempt to reproduce it..

**Comment by agalaguz** [comment]
@elnyry We found that the issue was on our side, a value for "errorDescription" had to be added to a message. In our particaular case it was empty. 
Sorry for the confusion, I am closing the issue. Have a good day!

**Comment by elnyry** [comment]
@agalaguz thanks for the confirmation. We ensured that it was working couple of sprints ago, good to see that there's no regression.

Good luck!
