### ISSUE TITLE
knex seed fails on duplicate key

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#1444]
**Summary**:
knex seed works only on empty tables, it fails silently on duplicate key

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
knex should insert new seed values successfully

**Steps to Reproduce**
I found an issue with the central-ledger data seed,  The data seed works properly only on empty tables. If we have some data in the table, the knex will try to insert duplicate entry and it will fail silently. Thus we will never get the new seed if they make any update to it.
e.g. Seed for `settlementWindowState`
Existing records:
```
mysql> select enumeration  from settlementWindowState;
+--------------------+
| enumeration        |
+--------------------+
| ABORTED            |
| CLOSED             |
| OPEN               |
| PENDING_SETTLEMENT |
| SETTLED            |
+--------------------+
5 rows in set (0.00 sec)
```
OSS added 2 new values to this table, but we not able to get those values. The knex insert fails silently with below error (This error is not logged anywhere)
```
Error: ER_DUP_ENTRY: Duplicate entry 'OPEN' for key 'PRIMARY'
    at Query.Sequence._packetToError (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Protocol._enqueue (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/knex/lib/dialects/mysql/index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/knex/lib/dialects/mysql/index.js:129:12)
    at Client_MySQL.query (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/knex/lib/client.js:169:17)
    at Runner.query (/Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/knex/lib/runner.js:134:36)
    at /Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/knex/lib/runner.js:40:23
    at /Users/shashi/Modusbox/DEV/Mojaloop/central-ledger/node_modules/knex/lib/runner.js:260:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlMessage: "Duplicate entry 'OPEN' for key 'PRIMARY'",
  sqlState: '23000',
  index: 0,
  sql: "insert into `settlementWindowState` (`description`, `enumeration`, `settlementWindowStateId`) values ('Current window into which Fulfilled transfers are being allocated. Only one window should be open at a time.', 'OPEN', 'OPEN'), ('Settlement Window is not accepting any additional transfers. All new transfers are being allocated to the OPEN Settlement Window.', 'CLOSED', 'CLOSED'), ('The net settlement report for this window has been taken, with the parameter set to indicate that settlement is to be processed.', 'PENDING_SETTLEMENT', 'PENDING_SETTLEMENT'), ('The Hub Operator/Settlement Bank has confirmed that all the participants that engaged in the settlement window have now settled their payments in accordance with the net settlement report.', 'SETTLED', 'SETTLED'), ('Window returned to this state when the settlement was not possible. This window may now be included in a future settlement.', 'ABORTED', 'ABORTED'), ('Intermediate state when closing a window.', 'PROCESSING', 'PROCESSING'), ('Used when close window processing failed and all retries have been exhausted.', 'FAILED', 'FAILED')"
}
```
To fix the issue, I deleted all the entries from that table and restarted the service, now we have correct entries
```
mysql> select enumeration  from settlementWindowState;
+--------------------+
| enumeration        |
+--------------------+
| ABORTED            |
| CLOSED             |
| FAILED             |
| OPEN               |
| PENDING_SETTLEMENT |
| PROCESSING         |
| SETTLED            |
+--------------------+
7 rows in set (0.00 sec)
```

**Specifications**
  - Component (if known): central-ledger
  - Version: v10.1.1 (or any other)
  - Platform: mowali
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @shashi165 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by mdebarros** [comment]
Possible changes to improve/fix this going forward:
1. All seed inserts should attempt to insert all values, and should not halt when a duplicate is found
2. QA tests should be enhanced to validate seeds (assuming they are available via the enum ADMIN API on central-ledger) <-- this can be used to validate new and upgraded Mojaloop installations.
