### ISSUE TITLE
GET /Transfers is failing

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1886]
**Summary**:

1. Get transferExtension is failing on GET Transfer request

```
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get] 2020-12-01T12:32:58.555Z - info: GetTransferHandler::getTransfer:get
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get] 2020-12-01T12:32:58.563Z - error: GetTransferHandler::getTransfer:get::validationFailed::Cannot read property 'find' of undefined--G0
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get] 2020-12-01T12:32:58.564Z - error: {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]   "type": "application/json",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]   "id": "015c49f1-fe76-4a22-b375-4569f27cae10",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]   "content": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]     "error": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "name": "FSPIOPError",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "cause": "TypeError: Cannot read property 'find' of undefined\n    at Object.getByTransferId (/opt/central-ledger/src/models/transfer/transferExtension.js:43:39)\n    at /opt/central-ledger/src/models/transfer/facade.js:153:71\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.getByIdLight (/opt/central-ledger/src/models/transfer/facade.js:126:12)\n    at async getTransfer (/opt/central-ledger/src/handlers/transfers/handler.js:562:22)",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "apiErrorCode": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "code": "2001",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "message": "Internal server error",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "name": "INTERNAL_SERVER_ERROR",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "type": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]           "regex": "^20[0-9]{2}$",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]           "description": "Generic Server Error",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]           "httpStatusCode": 500,
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]           "name": "GENERIC_SERVER_ERROR"
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         },
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "httpStatusCode": 500
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       },
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "httpStatusCode": 500,
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "useMessageAsDescription": false,
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "message": "Cannot read property 'find' of undefined",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "stack": "FSPIOPError: Cannot read property 'find' of undefined\n    at createFSPIOPError (/opt/central-ledger/node_modules/@mojaloop/central-services-error-handling/src/factory.js:198:12)\n    at Object.reformatFSPIOPError (/opt/central-ledger/node_modules/@mojaloop/central-services-error-handling/src/factory.js:319:12)\n    at Object.getByTransferId (/opt/central-ledger/src/models/transfer/transferExtension.js:45:32)\n    at /opt/central-ledger/src/models/transfer/facade.js:153:71\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.getByIdLight (/opt/central-ledger/src/models/transfer/facade.js:126:12)\n    at async getTransfer (/opt/central-ledger/src/handlers/transfers/handler.js:562:22)\nTypeError: Cannot read property 'find' of undefined\n    at Object.getByTransferId (/opt/central-ledger/src/models/transfer/transferExtension.js:43:39)\n    at /opt/central-ledger/src/models/transfer/facade.js:153:71\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.getByIdLight (/opt/central-ledger/src/models/transfer/facade.js:126:12)\n    at async getTransfer (/opt/central-ledger/src/handlers/transfers/handler.js:562:22)"
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]     }
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]   },
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]   "metadata": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]     "event": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "id": "9d805fe0-bc5f-41c1-92d1-eef25e3c8989",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "type": "log",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "action": "error",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "createdAt": "2020-12-01T12:32:58.564Z",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "state": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "status": "failed",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "code": "2001",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "description": "Internal server error"
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       }
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]     },
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]     "trace": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "startTimestamp": "2020-12-01T12:32:58.554Z",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "service": "cl_transfer_get",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "traceId": "1342505b93f6c9cfbb0eabe9aa87def6",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "spanId": "8221685b54693017",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "parentSpanId": "04d804a517012485",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "tags": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "tracestate": "mojaloop=eyJzcGFuSWQiOiI4MjIxNjg1YjU0NjkzMDE3In0=",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "transactionType": "transfer",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "transactionAction": "get",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "transactionId": "90a86218-51da-4ffb-9029-ed3967418f57",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "source": "payerfsp",
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "destination": "noresponsepayeefsp"
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       },
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       "tracestates": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         "mojaloop": {
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]           "spanId": "8221685b54693017"
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]         }
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]       }
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]     }
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get]   }
[d2-122-1-centralledger-handler-transfer-get-554c999fb9-r6m8m centralledger-handler-transfer-get] }
```

2. `transfer_negative_scenarios/payee_abort_v1.1` requests from Legacy Golden Path requests are using v1.0 for Content-Type and Accept headers

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
1. Standard GET /Transfer request flow from the legacy Golden Path: `transfer_negative_scenarios/payee_abort_v1.1`:
    1.1. GET /Transfer request by a PayerFSP should return the transfer state via the PUT /Transfer end-point to the PayerFSP
    1.2. The PUT /Transfer callback should contain the state of the transfer (i.e. "RECEIVED", "RESERVED", "ABORTED", "COMMITTED")
    1.3. The extensionList should be populated and include a "cause" extension indicating the errorCode and errorDescription if the state was aborted due to an errorCallback

2. Same as 1 above

**Steps to Reproduce**

1. 
    1.1. Send a transfer-prepare request as a PayerFSP
  1.2. Send a Error-callback in response as a PayeeFSP
  1.3. Send a GET /Transfer <-- the resultant callback will match the Error-callback send in step-2.

2. `transfer_negative_scenarios/payee_abort_v1.1` requests from Legacy Golden Path should be using v1.1 for both Content-Type and Accept headers

**Specifications**
  - Component (if known): Central-Ledger
  - Version: v11.x
  - Platform: n/a
  - Subsystem: Transfer Model
  - Type of testing:  manual
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by mdebarros** [comment]
Unable to reproduce
