### ISSUE TITLE
quoting service does not handle the partySubIdOrType in party

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#2103]
**Summary**:
The quoting service does not handle the partySubIdOrType in party, it gives below error
```
[dev1-quoting-service-57c765f8-78tsn quoting-service] (node:26) UnhandledPromiseRejectionWarning: FSPIOPError: Unsupported party identifier type '30' 
[dev1-quoting-service-57c765f8-78tsn quoting-service]     at Object.createFSPIOPError (/opt/quoting-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:198:12) 
[dev1-quoting-service-57c765f8-78tsn quoting-service]     at CachedDatabase.getPartyIdentifierType (/opt/quoting-service/src/data/database.js:330:36) 
[dev1-quoting-service-57c765f8-78tsn quoting-service]     at runMicrotasks (<anonymous>) 
[dev1-quoting-service-57c765f8-78tsn quoting-service]     at processTicksAndRejections (internal/process/task_queues.js:97:5) 
[dev1-quoting-service-57c765f8-78tsn quoting-service]     at async CachedDatabase.getCacheValue (/opt/quoting-service/src/data/cachedDatabase.js:109:17) 
[dev1-quoting-service-57c765f8-78tsn quoting-service]     at async CachedDatabase.createQuoteParty (/opt/quoting-service/src/data/database.js:479:35) 
[dev1-quoting-service-57c765f8-78tsn quoting-service]     at async QuotesModel.handleQuoteRequest (/opt/quoting-service/src/model/quotes.js:292:24) 
[dev1-quoting-service-57c765f8-78tsn quoting-service] (node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8) 

```

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
The POST /quotes should be processed successfully for `partySubIdOrType`

**Steps to Reproduce**
  1. send a quote request with partySubIdOrType
  
```
curl 'http://dev1-quoting-service/quotes'
  -H 'content-type: application/vnd.interoperability.quotes+json;version=1.0'
  -H 'accept: application/vnd.interoperability.quotes+json;version=1.0'
  -H 'date: Mon, 08 Mar 2021 14:44:32 GMT'
  -H 'fspiop-source: testingtoolkitdfsp'
  -H 'fspiop-destination: payeefsp'
  -H 'traceparent: 00-aabbb5baba213423f84f3ceba11c68ef-0123456789abcdef0-00'
  -H 'user-agent: axios/0.21.1'
  --data-binary '{"quoteId":"db60bb56-eea5-421e-a359-ec26ad1064fb","transactionId":"aa9acc0f-05c3-4651-bc07-b4973826d4bd","payer":{"partyIdInfo":{"partyIdType":"MSISDN","partyIdentifier":"44123456789","fspId":"testingtoolkitdfsp"},"personalInfo":{"complexName":{"firstName":"Firstname-Test","lastName":"Lastname-Test"},"dateOfBirth":"1984-01-01"}},"payee":{"partyIdInfo":{"partyIdType":"MSISDN","partyIdentifier":"27713803912","partySubIdOrType":"30","fspId":"payeefsp"}},"amountType":"RECEIVE","amount":{"amount":"100","currency":"USD"},"transactionType":{"scenario":"TRANSFER","initiator":"PAYER","initiatorType":"CONSUMER"},"note":"test"}'
  --compressed
```

  
**Specifications**
  - Component (if known): quoting-service
  - Version: v12.0.0
  - Platform: AWS / Mojaloop Switch
  - Subsystem: Core services
  - Type of testing: testing tool kit
  - Bug found/raised by: @shashi165 

**Notes**:
This issue is observed for the persistent mode. The pass-through mode will be fine, since it doesn’t involve storing quote request in the database.

**Pull Requests**:
- [x] https://github.com/mojaloop/central-ledger/pull/836
- [ ] https://github.com/mojaloop/quoting-service/pull/264

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by elnyry-sam-k** [comment]
Thanks for logging this @shashi165
