### ISSUE TITLE
account-lookup-service endpoints ambiguity 

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#2355]
**Summary**:
account-lookup-service endpoints ambiguity 
The following 2 endpoints are ambiguous  

`/parties/{Type}/{ID}/error`
`/parties/{Type}/{ID}/{SubId}`

When we make an error callback to `PUT /parties/{Type}/{ID}/error`, it's being picked up by the handler for `PUT /parties/{Type}/{ID}/{SubId}` and throwing validation error for body

**Request:** 
```
curl --location --request PUT 'http://localhost:4002/parties/MSISDN/212613123000/error' \
--header 'Accept: application/vnd.interoperability.parties+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.parties+json;version=1.0' \
--header 'FSPIOP-Source: testfsp4' \
--header 'Date: Sun, 15 Dec 2019 19:02:48 GMT' \
--header 'FSPIOP-Destination: testfsp3' \
--header 'fspiop-http-method: PUT' \
--header 'fspiop-uri: /parties/MSISDN/212613123000/error' \
--header 'fspiop-signature: {"signature":"oVRmwTIHK_NlIjcSFISp_Rvr8kV5aGkTSFfEK5hJ-dIEQWTcHtQS2gwl1LMugJXrqQa9WoLA6m5nGa8KO3xtK-qg0uK09jU0gS1slq8AAA-nsVP5qQHl2KIoPdF1kbyDv_oe5j5avno86mdgUM3Um76Pi1yKv05fCn5cEw5bcGCimmfIs_hobobY_AA1fIJiK9PWnOFVy0ZzCImFN_aqzEzJKKfb_zKuZbif4JAIoSjuNiAUBvIex5f1z_egj-SyL_xL9VFhtWIvDx2owO-rWIHvohLl8vYIysfuSGe9C-M-5lpjb13bZIqtjW8kYW2Y5BbW833FpIqbYKyeWYxZVA","protectedHeader":"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvcGFydGllcy9NU0lTRE4vMjEyNjEzMTIzMDAwL2Vycm9yIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUFVUIiwiRlNQSU9QLVNvdXJjZSI6InRlc3Rmc3A0IiwiRlNQSU9QLURlc3RpbmF0aW9uIjoidGVzdGZzcDMiLCJEYXRlIjoiV2VkLCAyMSBKdWwgMjAyMSAyMjoxNjozNiBHTVQifQ"}' \
--data-raw '{"errorInformation":{"errorCode":"3200","errorDescription":"Generic ID not found"}}'
```
**Error:**
```
2021-07-21T23:10:36.603Z - error: {
  "type": "application/json",
  "id": "836ad66a-e8b2-4fc3-9751-378b599701c8",
  "content": {
    "error": {
      "name": "FSPIOPError",
      "apiErrorCode": {
        "code": "3102",
        "message": "Missing mandatory element",
        "httpStatusCode": 400,
        "name": "MISSING_ELEMENT",
        "type": {
          "regex": "^31[0-9]{2}$",
          "description": "Client Validation Error",
          "httpStatusCode": 400,
          "name": "CLIENT_VALIDATION_ERROR"
        }
      },
      "httpStatusCode": 400,
      "useMessageAsDescription": false,
      "isBoom": true,
      "isServer": true,
      "data": null,
      "output": {
        "statusCode": 400,
        "payload": {
          "errorInformation": {
            "errorCode": "3102",
            "errorDescription": "Missing mandatory element - .requestBody should have required property 'party'"
          }
        },
        "headers": {}
      },
      "message": ".requestBody should have required property 'party'",
      "stack": "FSPIOPError: .requestBody should have required property 'party'\n    at createFSPIOPError (/Users/shashi/Modusbox/DEV/Mojaloop/account-lookup-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:198:12)\n    at Object.createFSPIOPErrorFromOpenapiError (/Users/shashi/Modusbox/DEV/Mojaloop/account-lookup-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:287:10)\n    at validationFail (/Users/shashi/Modusbox/DEV/Mojaloop/account-lookup-service/node_modules/@mojaloop/central-services-shared/src/util/openapiBackend.js:67:44)\n    at OpenAPIBackend.<anonymous> (/Users/shashi/Modusbox/DEV/Mojaloop/account-lookup-service/node_modules/openapi-backend/backend.js:247:32)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async OpenAPIBackend.handleRequest (/Users/shashi/Modusbox/DEV/Mojaloop/account-lookup-service/node_modules/openapi-backend/backend.js:161:26)\n    at async exports.Manager.execute (/Users/shashi/Modusbox/DEV/Mojaloop/account-lookup-service/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at async Object.internals.handler (/Users/shashi/Modusbox/DEV/Mojaloop/account-lookup-service/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at async exports.execute (/Users/shashi/Modusbox/DEV/Mojaloop/account-lookup-service/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at async Request._lifecycle (/Users/shashi/Modusbox/DEV/Mojaloop/account-lookup-service/node_modules/@hapi/hapi/lib/request.js:364:32)"
    }
  },
  "metadata": {
    "event": {
      "id": "23b725d5-4945-484f-ab65-26cada2db06d",
      "type": "log",
      "action": "error",
      "createdAt": "2021-07-21T23:10:36.603Z",
      "state": {
        "status": "failed",
        "code": "3102",
        "description": "Missing mandatory element - .requestBody should have required property 'party'"
      }
    },
    "trace": {
      "startTimestamp": "2021-07-21T23:10:36.594Z",
      "service": "PartiesSubIdByTypeAndIDPut",
      "traceId": "3376a1d3e7a3565d0153990b2ca8da37",
      "spanId": "1a2ab06c42886a8c",
      "tags": {
        "tracestate": "acmevendor=eyJzcGFuSWQiOiIxYTJhYjA2YzQyODg2YThjIn0="
      },
      "tracestates": {
        "acmevendor": {
          "spanId": "1a2ab06c42886a8c"
        }
      }
    }
  }
}

```

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
The account lookup service should handle the request properly and re-route the error message to the respective dfsp

**Steps to Reproduce**
  1. start the account-lookup-service
  2. run above postman request 
  

**Specifications**
  - Component (if known): account-lookup-service
  - Version: v11.0.1
  - Platform: mojaloop
  - Subsystem: account-lookup
  - Type of testing: 
  - Bug found/raised by: @shashi165 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by kleyow** [comment]
I believe the issue persists in <v11.0.1. 
Can you upgrade `account-lookup-service` to v11.7.0?
I believe the closest version that resolves this bug is v11.1.0. So you can use that if you want a closer version.

I have tested both v11.7.0 and v11.1.0 and the issue does not occur.

**Comment by shashi165** [comment]
Hi @kleyow , Thanks for checking it. I tested 11.7.0 version and I am still getting the same error, probably we can have a quick call to discuss it

**Comment by shashi165** [comment]
Ok, I did reinstall of the packages and the issue went away in the latest ALS version, so we can close the issue

**Comment by elnyry-sam-k** [comment]
Great outcome, thank you @shashi165 , @kleyow
