### ISSUE TITLE
EFK-APM Stack on test.mojaloop.live services are failing due to several errors

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2428]
**Summary**:

EFK-APM Stack on test.mojaloop.live services are failing due to several errors:

1. filebeat is failing on op1 and op2 nodes:
```log
CrashLoopBackOff: back-off 5m0s restarting failed container=filebeat pod=filebeat-beat-filebeat-v94sv_logging(985a242a-df5a-4610-97bf-7d30d7580312)
```

2. APM is showing Elasticsearch: 503 Service Unavailable error: 

```log
{"log.level":"error","@timestamp":"2021-08-24T15:04:53.188Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/output.go","file.line":154},"message":"Failed to connect to backoff(elasticsearch(http://elasticsearch-es-http.logging.svc:9200)): Connection marked as failed because the onConnect callback failed: could not connect to a compatible version of Elasticsearch: 503 Service Unavailable: {\"error\":{\"root_cause\":[{\"type\":\"master_not_discovered_exception\",\"reason\":null}],\"type\":\"master_not_discovered_exception\",\"reason\":null},\"status\":503}","ecs.version":"1.6.0"}
```
3. APM is showing connectivity errors to ElasticSearch: 

```log
{"log.level":"error","@timestamp":"2021-08-24T15:05:07.537Z","log.logger":"request","log.origin":{"file.name":"middleware/log_middleware.go","file.line":60},"message":"queue is full","url.original":"/intake/v2/events","http.request.method":"POST","user_agent.original":"elastic-apm-node/6.4.0-snapshot elastic-apm-http-client/7.3.0","source.address":"10.42.4.28","http.request.id":"e63a599d-cb56-45db-b7bc-c54b8e202d1e","event.duration":10998164182,"http.response.status_code":503,"error.message":"queue is full","ecs.version":"1.6.0"}
```

4. APM is showing `Queue Full` errors : 
```log
{"log.level":"error","@timestamp":"2021-08-24T15:05:07.537Z","log.logger":"request","log.origin":{"file.name":"middleware/log_middleware.go","file.line":60},"message":"queue is full","url.original":"/intake/v2/events","http.request.method":"POST","user_agent.original":"elastic-apm-node/6.4.0-snapshot elastic-apm-http-client/7.3.0","source.address":"10.42.4.28","http.request.id":"e63a599d-cb56-45db-b7bc-c54b8e202d1e","event.duration":10998164182,"http.response.status_code":503,"error.message":"queue is full","ecs.version":"1.6.0"}
```

5. ElasticSearch showing `No Disk Space` error:

```log
{"type": "server", "timestamp": "2021-08-24T15:06:57,586Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "elasticsearch", "node.name": "elasticsearch-es-default-1", "message": "path: /_license, params: {human=false}", "cluster.uuid": "uu9wushMRgWv1IBaBqQ4fA", "node.id": "Fs_h9EdeQ5KNgpfU3aYF3A" ,
"stacktrace": ["org.elasticsearch.discovery.MasterNotDiscoveredException: null",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:219) [elasticsearch-7.13.2.jar:7.13.2]",
"at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:324) [elasticsearch-7.13.2.jar:7.13.2]",
"at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:241) [elasticsearch-7.13.2.jar:7.13.2]",
"at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:590) [elasticsearch-7.13.2.jar:7.13.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.13.2.jar:7.13.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:831) [?:?]"] }
{"type": "server", "timestamp": "2021-08-24T15:06:57,888Z", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "elasticsearch", "node.name": "elasticsearch-es-default-1", "message": "this node is unhealthy: health check failed on [/usr/share/elasticsearch/data/nodes/0]", "cluster.uuid": "uu9wushMRgWv1IBaBqQ4fA", "node.id": "Fs_h9EdeQ5KNgpfU3aYF3A"  }
{"type": "server", "timestamp": "2021-08-24T15:07:00,592Z", "level": "ERROR", "component": "o.e.m.f.FsHealthService", "cluster.name": "elasticsearch", "node.name": "elasticsearch-es-default-1", "message": "health check of [/usr/share/elasticsearch/data/nodes/0] failed", "cluster.uuid": "uu9wushMRgWv1IBaBqQ4fA", "node.id": "Fs_h9EdeQ5KNgpfU3aYF3A" ,
"stacktrace": ["java.io.IOException: No space left on device",
```

**Severity**:
Low
**Priority**:
Medium

**Expected Behavior**

EFK-APM Stack services should be operating normally without errors, ingesting logs, and ESP events (traces, audits, etc).

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
outdated issue
