### ISSUE TITLE
POST Quotes fails when transactionId != transactionRequestId

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2719]
**Summary**:

POST Quotes will fail when transactionId != transactionRequestId due to the following error:

```LOG
2022-03-11T13:56:33.170Z - info: 2022-03-11T13:56:33.170Z, (1647006993142:moja2-quoting-service-6d96d7f749-42mr5:24:l0mg5uuj:10491) [quotesmodel]: Error in handleQuoteRequest for quoteId 10e95081-f6dd-48f8-9f08-3a7103a80718: FSPIOPError: insert into `quote` (`amount`, `amountTypeId`, `balanceOfPaymentsId`, `currencyId`, `expirationDate`, `note`, `quoteId`, `transactionInitiatorId`, `transactionInitiatorTypeId`, `transactionReferenceId`, `transactionRequestId`, `transactionScenarioId`, `transactionSubScenarioId`) values ('100.0000', 1, NULL, 'USD', NULL, DEFAULT, '10e95081-f6dd-48f8-9f08-3a7103a80718', 1, 1, 'f72fd595-2045-402b-b54d-c38f9f345f91', 'c2470148-1be2-4c0b-aece-aa8dcb92a6cc', 1, DEFAULT) - ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`central_ledger`.`quote`, CONSTRAINT `quote_transactionrequestid_foreign` FOREIGN KEY (`transactionRequestId`) REFERENCES `transactionReference` (`transactionReferenceId`))
    at createFSPIOPError (/opt/quoting-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:198:12)
    at Object.reformatFSPIOPError (/opt/quoting-service/node_modules/@mojaloop/central-services-error-handling/src/factory.js:333:12)
    at CachedDatabase.createQuote (/opt/quoting-service/src/data/database.js:699:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`central_ledger`.`quote`, CONSTRAINT `quote_transactionrequestid_foreign` FOREIGN KEY (`transactionRequestId`) REFERENCES `transactionReference` (`transactionReferenceId`))
```

This is caused by the following foreign key constraint:

```MYSQL
CONSTRAINT `quote_transactionrequestid_foreign` FOREIGN KEY (`transactionRequestId`) REFERENCES `transactionReference` (`transactionReferenceId`),
```

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

POST Quotes should be successful when transactionId != transactionRequestId.

**Steps to Reproduce**
  1. Create a POST Quotes request with transactionId != transactionRequestId.

**Specifications**
  - Component (if known): quoting-service
  - Version: v14.0.0
  - Platform: n/a
  - Subsystem: n/a
  - Type of testing: n/a
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: medium
- Priority when opened: medium

**Comment by mdebarros** [comment]
Issue tested with [v13.1.0 release](https://github.com/mojaloop/project/issues/2528) with updated [TTK v13.1.0 Test Collection](https://github.com/mojaloop/testing-toolkit-test-cases/pull/68).
