### ISSUE TITLE
[Bulk-API-Adapter] [Work-around] Incoming requests are failing with argument stream failure 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3260]
**Summary**:

> *NOTE: This is a temporary work-around documented in the [comment](https://github.com/mojaloop/project/issues/3260#issuecomment-1490094249) below. Actual fix will be done in https://github.com/mojaloop/project/issues/3263.*

Bulk-API-Adapter fails to process incoming requests (e.g. `http://localhost:8088/health` with the following error:

```
Debug: internal, implementation, error 
    TypeError: argument stream is required
    at getRawBody (/opt/app/node_modules/@mojaloop/central-services-shared/node_modules/raw-body/index.js:74:11)
    at method (/opt/app/node_modules/@mojaloop/central-services-shared/src/util/hapi/plugins/rawPayloadToDataUri.js:78:18)
    at exports.Manager.execute (/opt/app/node_modules/@hapi/hapi/lib/toolkit.js:57:29)
    at Request._invoke (/opt/app/node_modules/@hapi/hapi/lib/request.js:397:55)
    at Request._lifecycle (/opt/app/node_modules/@hapi/hapi/lib/request.js:370:86)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Request._execute (/opt/app/node_modules/@hapi/hapi/lib/request.js:280:9)
```

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

Incoming requests should be processed.

**Steps to Reproduce**
N/a

**Specifications**
  - Component (if known): bulk-api-adapter
  - Version: 15.0.2
  - Platform:
  - Subsystem: @mojaloop/central-services-shared: 17.5.1
  - Type of testing: n/a
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by mdebarros** [comment]
Temporary work-around has been applied to Bulk-API-Adapter by down-grading the Central-Services-Shared version from v17.5.1 to v17.5.0 --> https://github.com/mojaloop/bulk-api-adapter/pull/98

**Comment by mdebarros** [comment]
1. Work-around has been documented in comment: https://github.com/mojaloop/project/issues/3260#issuecomment-1490094249
2. Follow-up story to fix the issue can be found here: https://github.com/mojaloop/project/issues/3263
