### ISSUE TITLE
Quoting Service - throwing errors while processing quotes when LOG_LEVEL set to debug

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3604]
**Summary**:
When LOG_LEVEL environment variable is set to debug, the quoting service is not able to process the quoting requests. Observed the following errors in the log related to event-sdk.

```
2023-10-30T15:01:55.510Z - error: "ERROR - POST /quotes: TypeError: Cannot read properties of undefined (reading 'length')\n    at /opt/app/node_modules/@mojaloop/event-sdk/dist/transport/EventLoggingServiceClient.js:27:138\n    at new Promise (<anonymous>)\n    at EventLoggingServiceClient.log (/opt/app/node_modules/@mojaloop/event-sdk/dist/transport/EventLoggingServiceClient.js:19:16)\n    at DefaultSidecarRecorder.record (/opt/app/node_modules/@mojaloop/event-sdk/dist/Recorder.js:86:42)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Span.recordMessage (/opt/app/node_modules/@mojaloop/event-sdk/dist/Span.js:332:27)\n    at async Span.audit (/opt/app/node_modules/@mojaloop/event-sdk/dist/Span.js:241:22)\n    at async Quotes (/opt/app/src/handlers/quotes.js:86:7)\n    at async OpenAPIBackend.handleRequest (/opt/app/node_modules/openapi-backend/backend.js:215:26)\n    at async exports.Manager.execute (/opt/app/node_modules/@hapi/hapi/lib/toolkit.js:60:28)"
```

**Severity**:
Medium

**Priority**:
Critical

**Expected Behavior**
- Quoting service should process the quotes requests even when the log level set to debug

**Steps to Reproduce**
  1. Set the configuration to the following
    a. Enable event sidecar
    b. Set LOG_LEVEL to debug
  2. Deploy mojaloop helm chart
  3. Run provisioning collection
  4. Make a quotes request and observe the logs in quoting service

**Specifications**
  - Component (if known): Quoting service
  - Version: v15.4.0
  - Bug found/raised by: @vijayg10 @dfry

**Comment by elnyry-sam-k** [comment]
marking as high pri , and to be included for v15.2.0
