### ISSUE TITLE
Quote on simulator is failing on dev1 environment

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#659]
**Summary**:

Quotes request to Simulator as per the following CURL:
```
curl -X POST \
  http://dev1-interop-switch.mojaloop.live/interop/switch/v1/quotes \
  -H 'Accept: application/vnd.interoperability.quotes+json;version=1' \
  -H 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
  -H 'Date: Fri, 21 Dec 2018 12:19:49 GMT' \
  -H 'FSPIOP-Destination: payeefsp' \
  -H 'FSPIOP-SOurce: payerfsp' \
  -H 'Postman-Token: 549d21ad-73c3-4fd4-93b4-2ec327d0ae64' \
  -H 'cache-control: no-cache' \
  -d '{
  "quoteId": "ddaa67b3-5bf8-45c1-bfcf-1e8781177c37",
  "transactionId": "ddaa67b3-5bf8-45c1-bfcf-1e8781177c37",
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "{{receiverMSISDN}}",
      "fspId": "payeefsp"
    }
  },
  "payer": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "27713803905",
      "fspId": "payerfsp"
    },
    "personalInfo": {
      "complexName": {
        "firstName": "Mats",
        "lastName": "Hagman"
      },
      "dateOfBirth": "1983-10-25"
    }
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "hej"
}'
```

Fails with the resulting log:
```
[mojasim-simulator-6745dfc54f-6pmfd] Debug: internal, implementation, error
[mojasim-simulator-6745dfc54f-6pmfd] ReferenceError: Logger is not defined
[mojasim-simulator-6745dfc54f-6pmfd] at exports.getcorrelationId (/opt/simulators/src/payer/handler.js:147:3)
[mojasim-simulator-6745dfc54f-6pmfd] at module.exports.internals.Manager.execute (/opt/simulators/node_modules/hapi/lib/toolkit.js:42:106)
[mojasim-simulator-6745dfc54f-6pmfd] at Object.internals.handler (/opt/simulators/node_modules/hapi/lib/handler.js:52:48)
[mojasim-simulator-6745dfc54f-6pmfd] at exports.execute (/opt/simulators/node_modules/hapi/lib/handler.js:37:36)
[mojasim-simulator-6745dfc54f-6pmfd] at internals.Request._lifecycle (/opt/simulators/node_modules/hapi/lib/request.js:276:62)
[mojasim-simulator-6745dfc54f-6pmfd] at <anonymous>
[mojasim-simulator-6745dfc54f-6pmfd] at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
Quote response should be sent to the Central-Ledger

**Steps to Reproduce**
  1. Use CURL command to send a request to the dev1 simulator

**Specifications**
  - Component (if known): Simulator
  - Version: mojaloop/simulator:v5.1.0
  - Platform: dev1
  - Subsystem: n/a
  - Type of testing: n/a
  - Bug found/raised by: @sri-miriyala 

**Notes**:

- Severity when opened:
- Priority when opened:

**Pull Request**:

- [x] https://github.com/mojaloop/helm/pull/151

**Comment by mdebarros** [comment]
@sri-miriyala I believe the issue has been resolved. The Simulator issue was resolved with the subsequent release 5.2.0. Please confirm that the error is no longer occurring.
