### ISSUE TITLE
ML-API-Adapter accepts fulfil requests without transfer ID in URI

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#849]
**Summary**:
ML-API-Adapter accepts fulfil requests without transfer ID in URI results in a non-complaint Mojaloop error:

E.g.
```CURL
curl -X PUT \
  http://dev1-ml-api-adapter.mojaloop.live/transfers \
  -H 'Accept: application/vnd.interoperability.transfers+json;version=1' \
  -H 'Content-Type: application/vnd.interoperability.transfers+json;version=1' \
  -H 'Date: Fri, 21 Dec 2018 12:17:01 GMT' \
  -H 'FSPIOP-Destination: {{fsp_mockfsp01_id}}' \
  -H 'FSPIOP-Source: {{fsp_mockfsp02_id}}' \
  -H 'Postman-Token: 891f1fb9-73ce-4fcd-bc71-b79b9f14f470' \
  -H 'cache-control: no-cache' \
  -d '{
	"fulfilment": "XoSz1cL0tljJSCp_VtIYmPNw-zFUgGfbUqf69AagUzY",
	"completedTimestamp": "2019-07-08T13:56:01.412Z",
	"transferState": "COMMITTED"
}'
```

Response:

```HTTP
{
    "id": "NotFoundError",
    "message": "Not Found"
}
```

**Severity**:
Medium

**Priority**:
Low

**Expected Behavior**

The response should look similar to the following error:

```
{
    "errorInformation": {
        "errorCode": 400,
        "errorDescription": "Bad Request",
        "extensionList": {
            "extension": [
                {
                    "key": "joiValidationError",
                    "value": "\"transferId\" parameter is missing from URI"
                }
            ]
        }
    }
}
```

**Steps to Reproduce**
  1. Curl as per the summary from Postman or CLI
  2. Monitor response message.

**Specifications**
  - Component (if known): ML-API-Adapter
  - Version: v6.x
  - Platform: all
  - Subsystem: n/a
  - Type of testing: manual
  - Bug found/raised by: @ggrg @mdebarros 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Low

**Comment by mdebarros** [comment]
Note that this issue should only exists with ML-API-Adapter. API,s that are generated using Swaggers should validate and handle this appropriately. I would recommend that tests are added to QA Framework to include this as part of the usual tests.

**Comment by lewisdaly** [comment]
I can replicate this issue with `v6.2.1` of the ml-api-adapter locally.

**Comment by elnyry** [comment]
Yep, we have this with ALS as well - #910 .. similar issue on different end-points..

**Comment by lewisdaly** [comment]
This doesn't seem to be an issue (or maybe a different issue) in the latest release: `v7.2.1`.

Example response:
```json
{
    "errorInformation": {
        "errorCode": "3002",
        "errorDescription": "Unknown URI - Not Found",
        "extensionList": [
            {
                "key": "cause",
                "value": "Error: Not Found\n    at internals.notFound (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/core.js:623:16)\n    at module.exports.internals.Manager.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/toolkit.js:41:33)\n    at Object.internals.handler (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:46:48)\n    at exports.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:31:36)\n    at Request._lifecycle (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/request.js:312:68)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
            },
            {
                "key": "cause",
                "value": "{\"stack\":\"Error: Not Found\\n    at internals.notFound (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/core.js:623:16)\\n    at module.exports.internals.Manager.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/toolkit.js:41:33)\\n    at Object.internals.handler (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:46:48)\\n    at exports.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:31:36)\\n    at Request._lifecycle (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/request.js:312:68)\\n    at process._tickCallback (internal/process/next_tick.js:68:7)\",\"data\":null,\"isBoom\":true,\"isServer\":false,\"output\":{},\"message\":\"Not Found\"}"
            }
        ]
    }
}
```

**Comment by lewisdaly** [comment]
This looks much closer to the spec. The `errorDescription` is incorrect however. 

According to the spec for errorCode `3002,` the errorDescription should be: `"Provided URI was unknown to the server"`

**Comment by elnyry** [comment]
Thanks Lewis. Unless anyone can repro it before we close out #910 , I think we can consider this closed and we need a separate bug (low) for the errorDescription aspect. I'll bring up the errorDescription issue at the standup today..

**Comment by lewisdaly** [comment]
FYI this error message seems to be coming from the `@modusbox/mojaloop-sdk-standard-components`

https://github.com/modusbox/mojaloop-sdk-standard-components/blob/master/src/lib/errors/index.js#L40

**Comment by lewisdaly** [comment]
Follow up low-priority ticket about the error message: https://github.com/mojaloop/project/issues/917

**Comment by oderayi** [comment]
With current release (7.4.0) in DEV2:

```JSON
{
    "errorInformation": {
        "errorCode": "3002",
        "errorDescription": "Unknown URI - Not Found",
        "extensionList": {
            "extension": [
                {
                    "key": "cause",
                    "value": "FSPIOPError: Not Found\n    at Object.createFSPIOPError (/opt/ml-api-adapter/node_modules/@mojaloop/central-services-error-handli"
                }
            ]
        }
    }
}
```

**Comment by elnyry** [comment]
Closing this now.. regarding extension list element key/value to point out that the ID is missing, that can be done later. Currently this conforms to the spec..
