### ISSUE TITLE
GET /parties not returning error code and msg as per API spec when ID value missing in the URI 

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#910]
**Summary**:
When I send a request with missing required URI parameter for the GET /parties call, payer FSP is not receiving the error code and error msgs as per API spec.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
Expected Response code: `404`
Expected Error code: `3102`
Expected error message: `Missing the required ID value in the URI`

**Steps to Reproduce**
  1. send GET /parties
  2. Check the simulator logs 

My request is:
```bash
curl -X GET \
  http://dev1-account-lookup.mojaloop.live/parties/MSISDN/ \
  -H 'Accept: application/vnd.interoperability.participants+json;version=1' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
  -H 'Date: Wed, 07 Aug 2019 00:46:31 GMT' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'Host: dev1-account-lookup.mojaloop.live' \
  -H 'User-Agent: PostmanRuntime/7.15.2'
```
Example Response:
```json
{
    "statusCode": 404,
    "error": "Not Found",
    "message": {
        "errorInformation": {
            "errorDescription": "Not Found",
            "extensionList": [
                {
                    "key": "",
                    "value": ""
                }
            ]
       }
  }
}
```

**Specifications**
  - Component (if known): ALS
  - Version:
  - Platform: MacOS
  - Subsystem: Mojaloop
  - Type of testing: API
  - Bug found/raised by: @sri-miriyala 

**Notes**:
- Severity when opened: High
- Priority when opened: Medium

**Comment by lewisdaly** [comment]
@elnyry @sri-miriyala What is the response supposed to look like? Is it the same as/similar to #849?

```json
{
    "errorInformation": {
        "errorCode": "3002",
        "errorDescription": "Unknown URI - Not Found",
        "extensionList": [
            {
                "key": "cause",
                "value": "Error: Not Found\n    at internals.notFound (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/core.js:623:16)\n    at module.exports.internals.Manager.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/toolkit.js:41:33)\n    at Object.internals.handler (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:46:48)\n    at exports.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:31:36)\n    at Request._lifecycle (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/request.js:312:68)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
            },
            {
                "key": "cause",
                "value": "{\"stack\":\"Error: Not Found\\n    at internals.notFound (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/core.js:623:16)\\n    at module.exports.internals.Manager.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/toolkit.js:41:33)\\n    at Object.internals.handler (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:46:48)\\n    at exports.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:31:36)\\n    at Request._lifecycle (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/request.js:312:68)\\n    at process._tickCallback (internal/process/next_tick.js:68:7)\",\"data\":null,\"isBoom\":true,\"isServer\":false,\"output\":{},\"message\":\"Not Found\"}"
            }
        ]
    }
}
```

**Comment by lewisdaly** [comment]
I'm able to reproduce locally with the latest master branch, so unlike the other case, it looks like this needs to be fixed.

**Comment by oderayi** [comment]
Response from this endpoint, with the v7.4.0:

```JSON
{
    "errorInformation": {
        "errorCode": "3002",
        "errorDescription": "Unknown URI - Not Found",
        "extensionList": {
            "extension": [
                {
                    "key": "cause",
                    "value": "FSPIOPError: Not Found\n    at Object.createFSPIOPError (/opt/account-lookup-service/node_modules/@mojaloop/central-services-erro"
                }
            ]
        }
    }
}
```

**Comment by elnyry** [comment]
Thanks @oderayi , this looks good..

@sri-miriyala please confirm, if this looks ok..

**Comment by amarmodus** [comment]
@elnyry As per bug, Expected error code was 3102 and the present error code is 3002.
Expected error message: Missing the required ID value in the URI

**Comment by elnyry** [comment]
@amarmodus I'd say thats debatable.. typically, 3102 is used for data model for calls such as PUT / POST that have message bodies. For this one, I think it can be argued that its a URI issue (as it relates to a missing URI param)

**Comment by elnyry** [comment]
Please re-open if there's any further issue or repro. seems good so far.

**Comment by sri-miriyala** [comment]
@elnyry to me unknown URI is not telling me what is wrong with the URI I Provided. Where as missing MSISDN is clearly telling me the issue with the client request and why switch is rejecting it.
