### ISSUE TITLE
Incorrect Error message for error code 3002 in ml-api-adapter

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#917]
**Summary**:
Follow up from: #849.

The `errorDescription` for an unknown endpoint is incorrect according to version 1.0 of the API Spec. 

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**

The `errorDescription` should be: `"Provided URI was unknown to the server"`

**Steps to Reproduce**
1. Send a request to an unknown endpoint on the `ml-api-adapter`:
```bash
curl -X PUT \
  http://dev1-ml-api-adapter.mojaloop.live/transfers \
  -H 'Accept: application/vnd.interoperability.transfers+json;version=1' \
  -H 'Content-Type: application/vnd.interoperability.transfers+json;version=1' \
  -H 'Date: Fri, 21 Dec 2018 12:17:01 GMT' \
  -H 'FSPIOP-Destination: {{fsp_mockfsp01_id}}' \
  -H 'FSPIOP-Source: {{fsp_mockfsp02_id}}' \
  -H 'Postman-Token: 891f1fb9-73ce-4fcd-bc71-b79b9f14f470' \
  -H 'cache-control: no-cache' \
  -d '{
	"fulfilment": "XoSz1cL0tljJSCp_VtIYmPNw-zFUgGfbUqf69AagUzY",
	"completedTimestamp": "2019-07-08T13:56:01.412Z",
	"transferState": "COMMITTED"
}'
```
2. Observe the response:
```json
{
    "errorInformation": {
        "errorCode": "3002",
        "errorDescription": "Unknown URI - Not Found",
        "extensionList": [
            {
                "key": "cause",
                "value": "Error: Not Found\n    at internals.notFound (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/core.js:623:16)\n    at module.exports.internals.Manager.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/toolkit.js:41:33)\n    at Object.internals.handler (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:46:48)\n    at exports.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:31:36)\n    at Request._lifecycle (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/request.js:312:68)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
            },
            {
                "key": "cause",
                "value": "{\"stack\":\"Error: Not Found\\n    at internals.notFound (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/core.js:623:16)\\n    at module.exports.internals.Manager.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/toolkit.js:41:33)\\n    at Object.internals.handler (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:46:48)\\n    at exports.execute (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/handler.js:31:36)\\n    at Request._lifecycle (/Users/ldaly/developer/vessels/mojaloop-github/ml-api-adapter/node_modules/@hapi/hapi/lib/request.js:312:68)\\n    at process._tickCallback (internal/process/next_tick.js:68:7)\",\"data\":null,\"isBoom\":true,\"isServer\":false,\"output\":{},\"message\":\"Not Found\"}"
            }
        ]
    }
}
```
3. Note that the `errorDescription` field contains an incorrect message.

**Actual:** `"Unknown URI - Not Found"`
**Expected:** `"Provided URI was unknown to the server"`

**Specifications**
  - Component (if known): ml-api-adapter -> @modusbox/mojaloop-sdk-standard-components package
  - Version: 7.1.2
  - Platform: any
  - Type of testing: 
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: Low
- Priority when opened: Low

**Comment by elnyry** [comment]
PR - https://github.com/mojaloop/sdk-standard-components/pull/10

**Comment by elnyry** [comment]
Updated the error list for uniformity and reflect the names from the API Definition in the sdk components used for error handling and this is now used in the central services, so closing this (as this is in fact the message from the Spec).
