### ISSUE TITLE
Bulk transfers DB authentication issue for inserts

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#947]
**Summary**:
On a POST /bulkTransfers request, getting a 500 - Internal Server Error

**Severity**:
Medium

**Priority**:
Low

**Expected Behavior**
On a POST /bulkTransfers, a 202 is sent to the entity making the call and the POST call is relayed to the Payee FSP as it is received.

**Steps to Reproduce**
  1. On a POST /bulkTransfers request
```
{
    "message": "An internal server error occurred",
    "statusCode": 500,
    "error": "Internal Server Error"
}
```
2. Logs from the bulk api adapter
```
(node:1) UnhandledPromiseRejectionWarning: MongoError: command insert requires authentication 
    at Connection.<anonymous> (/opt/bulk-api-adapter/node_modules/mongodb-core/lib/connection/pool.js:443:61) 
    at Connection.emit (events.js:189:13) 
    at processMessage (/opt/bulk-api-adapter/node_modules/mongodb-core/lib/connection/connection.js:364:10) 
    at Socket.<anonymous> (/opt/bulk-api-adapter/node_modules/mongodb-core/lib/connection/connection.js:533:15) 
    at Socket.emit (events.js:189:13) 
    at addChunk (_stream_readable.js:284:12) 
    at readableAddChunk (_stream_readable.js:265:11) 
    at Socket.Readable.push (_stream_readable.js:220:10) 
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) 
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) 
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
2019-08-22T11:28:41.931Z - : command insert requires authentication 
```

**Specifications**
  - Component (if known): central services
  - Version: v7.4.1 (helm)
  - Platform: AWS Dev
  - Subsystem: bulk-api-adapter
  - Type of testing: functional 
  - Bug found/raised by: @elnyry 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Low

Request used:
```
curl -X POST \
  http://dev2-bulk-api-adapter.mojaloop.live/bulkTransfers \
  -H 'Accept: application/vnd.interoperability.bulkTransfers+json;version=1' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 2273' \
  -H 'Content-Type: application/vnd.interoperability.bulkTransfers+json;version=1.0' \
  -H 'Date: Thu, 22 Aug 2019 11:46:57 GMT' \
  -H 'FSPIOP-Destination: {{payeeFsp}}' \
  -H 'FSPIOP-HTTP-Method: POST' \
  -H 'FSPIOP-Signature: {"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}' \
  -H 'FSPIOP-Source: {{payerFsp}}' \
  -H 'FSPIOP-URI: /bulkTransfers' \
  -H 'Host: dev2-bulk-api-adapter.mojaloop.live' \
  -H 'Postman-Token: 96d9c661-4d14-400a-8d9f-fad6e2fb46d5,8a4b75fa-3670-4201-881f-9744a725ec29' \
  -H 'User-Agent: PostmanRuntime/7.15.2' \
  -H 'cache-control: no-cache' \
  -d '{ 
    "bulkTransferId": "93f0c657-c771-4162-bd41-a9d411cf2216",
    "bulkQuoteId": "93f0c657-c771-4162-bd41-a9d411cf2216",
    "payeeFsp": "{{payeeFsp}}",
    "payerFsp": "{{payerFsp}}",
    "individualTransfers":
    [ {
        "transferId": "6b24a393-cdf5-4be1-9057-e4a8cf49a34a",
        "transferAmount": {
            "currency": "USD",
            "amount": "1"
        },
        "ilpPacket": "AYIBgQAAAAAAAASwNGxldmVsb25lLmRmc3AxLm1lci45T2RTOF81MDdqUUZERmZlakgyOVc4bXFmNEpLMHlGTFGCAUBQU0svMS4wCk5vbmNlOiB1SXlweUYzY3pYSXBFdzVVc05TYWh3CkVuY3J5cHRpb246IG5vbmUKUGF5bWVudC1JZDogMTMyMzZhM2ItOGZhOC00MTYzLTg0NDctNGMzZWQzZGE5OGE3CgpDb250ZW50LUxlbmd0aDogMTM1CkNvbnRlbnQtVHlwZTogYXBwbGljYXRpb24vanNvbgpTZW5kZXItSWRlbnRpZmllcjogOTI4MDYzOTEKCiJ7XCJmZWVcIjowLFwidHJhbnNmZXJDb2RlXCI6XCJpbnZvaWNlXCIsXCJkZWJpdE5hbWVcIjpcImFsaWNlIGNvb3BlclwiLFwiY3JlZGl0TmFtZVwiOlwibWVyIGNoYW50XCIsXCJkZWJpdElkZW50aWZpZXJcIjpcIjkyODA2MzkxXCJ9IgA",
        "condition": "f5sqb7tBTWPd5Y8BDFdMm9BJR_MNI4isf8p8n4D5pHA",
        "extensionList": { "extension": [
            { "key": "key1", "value": "value1"},
            { "key": "key2", "value": "value2"}
        ] }
      },
      {
        "transferId": "e2fa20ee-7214-4f2e-abe5-b858bf069c07",
        "transferAmount": {
            "currency": "USD",
            "amount": "2"
        },
        "ilpPacket": "AYIBgQAAAAAAAASwNGxldmVsb25lLmRmc3AxLm1lci45T2RTOF81MDdqUUZERmZlakgyOVc4bXFmNEpLMHlGTFGCAUBQU0svMS4wCk5vbmNlOiB1SXlweUYzY3pYSXBFdzVVc05TYWh3CkVuY3J5cHRpb246IG5vbmUKUGF5bWVudC1JZDogMTMyMzZhM2ItOGZhOC00MTYzLTg0NDctNGMzZWQzZGE5OGE3CgpDb250ZW50LUxlbmd0aDogMTM1CkNvbnRlbnQtVHlwZTogYXBwbGljYXRpb24vanNvbgpTZW5kZXItSWRlbnRpZmllcjogOTI4MDYzOTEKCiJ7XCJmZWVcIjowLFwidHJhbnNmZXJDb2RlXCI6XCJpbnZvaWNlXCIsXCJkZWJpdE5hbWVcIjpcImFsaWNlIGNvb3BlclwiLFwiY3JlZGl0TmFtZVwiOlwibWVyIGNoYW50XCIsXCJkZWJpdElkZW50aWZpZXJcIjpcIjkyODA2MzkxXCJ9IgA",
        "condition": "f5sqb7tBTWPd5Y8BDFdMm9BJR_MNI4isf8p8n4D5pHA",
        "extensionList": { "extension": [
            { "key": "key1", "value": "value1"},
            { "key": "key2", "value": "value2"}
        ] }
    } ],
    "expiration": "2019-08-22T12:46:57.670Z",
    "extensionList": { "extension": [
        { "key": "key1", "value": "value1"},
        { "key": "key2", "value": "value2"}
    ] }
}'
```

**Comment by ggrg** [comment]
Just checking what I'm currently assigned to. Guys, is there any way you can think of to reproduce this locally? Maybe require password for MongoDB? I'm not sure **Expected Behavior** is correct, if MongoDB is unavailable for any reason. The response seems right to me.

**Comment by elnyry** [comment]
@ggrg , I think this specific issue is now fixed, with v8.1.0 of Helm. However, the transfers are still not going through - this needs investigation. Its probably still a setup issue; We'll need to investigate before we can say otherwise.

**Comment by elnyry** [comment]
@ggrg the original issue is now fixed..

However, seeing the below in bulk-prepare-handler, not sure what validation is failing though, will need investigation. (this was on dev1)

```
2019-10-24T10:23:54.355Z - : BulkPrepareHandler::bulkPrepare 
2019-10-24T10:23:54.355Z - : BulkPrepareHandler::bulkPrepare::dupCheck 
2019-10-24T10:23:54.362Z - : BulkPrepareHandler::bulkPrepare::validationFailed 
2019-10-24T10:23:54.362Z - : BulkPrepareHandler::bulkPrepare::validationFailed::saveInvalidRequest 
2019-10-24T10:23:54.367Z - : BulkPrepareHandler::bulkPrepare::validationFailed::saveInvalidRequest::callbackErrorGeneric--BP8 
2019-10-24T10:23:54.367Z - : BulkPrepareHandler::bulkPrepare::validationFailed::saveInvalidRequest::callbackErrorGeneric--BP8::notImplemented 
2019-10-24T10:31:38.454Z - : BulkPrepareHandler::bulkPrepare 
2019-10-24T10:31:38.454Z - : BulkPrepareHandler::bulkPrepare::dupCheck 
2019-10-24T10:31:38.459Z - : BulkPrepareHandler::bulkPrepare::validationFailed 
2019-10-24T10:31:38.459Z - : BulkPrepareHandler::bulkPrepare::validationFailed::saveInvalidRequest 
2019-10-24T10:31:38.463Z - : BulkPrepareHandler::bulkPrepare::validationFailed::saveInvalidRequest::callbackErrorGeneric--BP8 
2019-10-24T10:31:38.463Z - : BulkPrepareHandler::bulkPrepare::validationFailed::saveInvalidRequest::callbackErrorGeneric--BP8::notImplemented 
```

**Comment by elnyry** [comment]
This issue is now confirmed as resolved.. Tested on AWS 'dev1' with Helm v8.1.0. However, to further enhance QA on bulk transfers, simulator needs to support bulk transfers --> #1033
