### ISSUE TITLE
`participant_inactive_stop_tranfers` Test fails on `Send Transfer fail`

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#954]
**Summary**:

Golden path failure `participant_inactive_stop_tranfers` Test fails on `Send Transfer fail`

Log files from the Central Ledger Prepare Handler:
```java
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] 2019-08-28T11:56:53.566Z - info: PrepareHandler::prepare
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] 2019-08-28T11:56:53.566Z - info: PrepareHandler::prepare::dupCheck
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] .returning() is not supported by mysql and will not have any effect.
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] 2019-08-28T11:56:53.571Z - error: PrepareHandler::prepare::validationFailed
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] 2019-08-28T11:56:53.571Z - info: PrepareHandler::prepare::validationFailed::saveInvalidRequest
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] 2019-08-28T11:56:53.578Z - info: PrepareHandler::prepare::validationFailed::saveInvalidRequest::callbackErrorGeneric--P7
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] .returning() is not supported by mysql and will not have any effect.
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] 2019-08-28T11:56:53.580Z - error: Consumer::consume()::syncQueue.queue - error: {"message":"PrepareHandler::prepare::validationFailed::saveInvalidRequest::callbackErrorGeneric--P7::insert into `transferError` (`errorCode`, `errorDescription`, `transferId`, `transferStateChangeId`) values ('Participant payerfsp is inactive', DEFAULT, 281, '3100') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'Participant payerfsp is inactive' for column 'errorCode' at row 1--P0","apiErrorCode":{"code":"2001","message":"Internal server error","name":"INTERNAL_SERVER_ERROR","type":{"regex":"^20[0-9]{2}$","description":"Generic Server Error","name":"GENERIC_SERVER_ERROR"}},"cause":"Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'Participant payerfsp is inactive' for column 'errorCode' at row 1n    at Query.Sequence._packetToError (/opt/central-ledger/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)n    at Query.ErrorPacket (/opt/central-ledger/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)n    at Protocol._parsePacket (/opt/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:291:23)n    at Parser._parsePacket (/opt/central-ledger/node_modules/mysql/lib/protocol/Parser.js:433:10)n    at Parser.write (/opt/central-ledger/node_modules/mysql/lib/protocol/Parser.js:43:10)n    at Protocol.write (/opt/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:38:16)n    at Socket.<anonymous> (/opt/central-ledger/node_modules/mysql/lib/Connection.js:91:28)n    at Socket.<anonymous> (/opt/central-ledger/node_modules/mysql/lib/Connection.js:525:10)n    at Socket.emit (events.js:189:13)n    at addChunk (_stream_readable.js:284:12)n    at readableAddChunk (_stream_readable.js:265:11)n    at Socket.Readable.push (_stream_readable.js:220:10)n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)n    --------------------n    at Protocol._enqueue (/opt/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:144:48)n    at Connection.query (/opt/central-ledger/node_modules/mysql/lib/Connection.js:201:25)n    at /opt/central-ledger/node_modules/knex/lib/dialects/mysql/index.js:130:18n    at Promise._execute (/opt/central-ledger/node_modules/bluebird/js/release/debuggability.js:313:9)n    at Promise._resolveFromExecutor (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:488:18)n    at new Promise (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:79:10)n    at Client_MySQL._query (/opt/central-ledger/node_modules/knex/lib/dialects/mysql/index.js:124:12)n    at Client_MySQL.query (/opt/central-ledger/node_modules/knex/lib/client.js:158:17)n    at Runner.query (/opt/central-ledger/node_modules/knex/lib/runner.js:135:36)n    at /opt/central-ledger/node_modules/knex/lib/runner.js:39:23n    at tryCatcher (/opt/central-ledger/node_modules/bluebird/js/release/util.js:16:23)n    at /opt/central-ledger/node_modules/bluebird/js/release/using.js:185:26n    at tryCatcher (/opt/central-ledger/node_modules/bluebird/js/release/util.js:16:23)n    at Promise._settlePromiseFromHandler (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:517:31)n    at Promise._settlePromise (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:574:18)n    at Promise._settlePromise0 (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:619:10)n    at Promise._settlePromises (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:699:18)n    at Promise._fulfill (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:643:18)n    at PromiseArray._resolve (/opt/central-ledger/node_modules/bluebird/js/release/promise_array.js:126:19)n    at PromiseArray._promiseFulfilled (/opt/central-ledger/node_modules/bluebird/js/release/promise_array.js:144:14)n    at Promise._settlePromise (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:579:26)n    at Promise._settlePromise0 (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:619:10)n    at Promise._settlePromises (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:699:18)n    at _drainQueueStep (/opt/central-ledger/node_modules/bluebird/js/release/async.js:138:12)n    at _drainQueue (/opt/central-ledger/node_modules/bluebird/js/release/async.js:131:9)n    at Async._drainQueues (/opt/central-ledger/node_modules/bluebird/js/release/async.js:147:5)n    at Immediate.Async.drainQueues (/opt/central-ledger/node_modules/bluebird/js/release/async.js:17:14)n    at runCallback (timers.js:705:18)n    at tryOnImmediate (timers.js:676:5)n    at processImmediate (timers.js:658:5)"}
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] 2019-08-28T11:56:53.581Z - error: Consumer::onError()[topics='topic-transfer-prepare'] - FSPIOPError: PrepareHandler::prepare::validationFailed::saveInvalidRequest::callbackErrorGeneric--P7::insert into `transferError` (`errorCode`, `errorDescription`, `transferId`, `transferStateChangeId`) values ('Participant payerfsp is inactive', DEFAULT, 281, '3100') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'Participant payerfsp is inactive' for column 'errorCode' at row 1--P0
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at createFSPIOPError (/opt/central-ledger/node_modules/@mojaloop/central-services-error-handling/src/factory.js:173:12)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Object.createInternalServerFSPIOPError (/opt/central-ledger/node_modules/@mojaloop/central-services-error-handling/src/factory.js:224:10)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at prepare (/opt/central-ledger/src/handlers/transfers/handler.js:180:32)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'Participant payerfsp is inactive' for column 'errorCode' at row 1
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Query.Sequence._packetToError (/opt/central-ledger/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Query.ErrorPacket (/opt/central-ledger/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Protocol._parsePacket (/opt/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:291:23)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Parser._parsePacket (/opt/central-ledger/node_modules/mysql/lib/protocol/Parser.js:433:10)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Parser.write (/opt/central-ledger/node_modules/mysql/lib/protocol/Parser.js:43:10)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Protocol.write (/opt/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:38:16)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Socket.<anonymous> (/opt/central-ledger/node_modules/mysql/lib/Connection.js:91:28)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Socket.<anonymous> (/opt/central-ledger/node_modules/mysql/lib/Connection.js:525:10)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Socket.emit (events.js:189:13)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at addChunk (_stream_readable.js:284:12)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at readableAddChunk (_stream_readable.js:265:11)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Socket.Readable.push (_stream_readable.js:220:10)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] --------------------
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Protocol._enqueue (/opt/central-ledger/node_modules/mysql/lib/protocol/Protocol.js:144:48)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Connection.query (/opt/central-ledger/node_modules/mysql/lib/Connection.js:201:25)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at /opt/central-ledger/node_modules/knex/lib/dialects/mysql/index.js:130:18
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._execute (/opt/central-ledger/node_modules/bluebird/js/release/debuggability.js:313:9)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._resolveFromExecutor (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:488:18)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at new Promise (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:79:10)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Client_MySQL._query (/opt/central-ledger/node_modules/knex/lib/dialects/mysql/index.js:124:12)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Client_MySQL.query (/opt/central-ledger/node_modules/knex/lib/client.js:158:17)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Runner.query (/opt/central-ledger/node_modules/knex/lib/runner.js:135:36)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at /opt/central-ledger/node_modules/knex/lib/runner.js:39:23
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at tryCatcher (/opt/central-ledger/node_modules/bluebird/js/release/util.js:16:23)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at /opt/central-ledger/node_modules/bluebird/js/release/using.js:185:26
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at tryCatcher (/opt/central-ledger/node_modules/bluebird/js/release/util.js:16:23)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._settlePromiseFromHandler (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:517:31)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._settlePromise (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:574:18)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._settlePromise0 (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:619:10)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._settlePromises (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:699:18)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._fulfill (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:643:18)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at PromiseArray._resolve (/opt/central-ledger/node_modules/bluebird/js/release/promise_array.js:126:19)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at PromiseArray._promiseFulfilled (/opt/central-ledger/node_modules/bluebird/js/release/promise_array.js:144:14)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._settlePromise (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:579:26)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._settlePromise0 (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:619:10)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Promise._settlePromises (/opt/central-ledger/node_modules/bluebird/js/release/promise.js:699:18)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at _drainQueueStep (/opt/central-ledger/node_modules/bluebird/js/release/async.js:138:12)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at _drainQueue (/opt/central-ledger/node_modules/bluebird/js/release/async.js:131:9)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Async._drainQueues (/opt/central-ledger/node_modules/bluebird/js/release/async.js:147:5)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at Immediate.Async.drainQueues (/opt/central-ledger/node_modules/bluebird/js/release/async.js:17:14)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at runCallback (timers.js:705:18)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at tryOnImmediate (timers.js:676:5)
[d274301-centralledger-handler-transfer-prepare-5f6977c587-gnwz5 centralledger-handler-transfer-prepare] at processImmediate (timers.js:658:5))
```

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
1. Golden path `participant_inactive_stop_tranfers` Test on `Send Transfer fail` should pass
2. Transfer Error should be inserted successfully into the `transferError`, and the 

**Steps to Reproduce**
  1. Run Golden Path against Dev2 using Mojaloop Helm Chart 7.4.3

**Specifications**
  - Component (if known): Central-ledger
  - Version: v7.4.1
  - Platform: dev2
  - Subsystem: n/a
  - Type of testing: manual
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Pull Request**:
- [x] https://github.com/mojaloop/central-ledger/pull/373
- [x] https://github.com/mojaloop/postman/pull/36

**Comment by mdebarros** [comment]
https://www.dropbox.com/s/u65ami6ykaopzcs/Screenshot%202019-08-29%2015.16.55.png?dl=0
