### ISSUE TITLE
Intermittent CI failures for vulnerability-check

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#958]
**Summary**:
The `vulnerability-check`step occasionally fails on CI/CD across all projects.

See this failure for an example: https://circleci.com/gh/mojaloop/ml-api-adapter/3619

The test fails with:
```
Error: 'npm audit' failed with ENOAUDIT. Check the log above for more details.
    at npmFacade.runNpmCommand.then.input (/home/circleci/project/node_modules/npm-audit-resolver/check.js:39:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Exited with code 2
```

Some light googling suggested this could be an issue with the npm audit server itself (ENOAUDIT seems to get called on a 500 error). So we are going to add some logging for now and revisit this when we have better logs. The worry is that we are getting rate limited, which we won't be able to do much about.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
The `npm run audit:check` should run successfully, and not print the `ENOAUDIT` error message

**Steps to Reproduce**
  1. This happens intermittently and occasionally across all projects with the `vulnerability-check` 
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by lewisdaly** [comment]
Added some logging to `central-ledger`, hopefully that will help us catch this issue.

**Comment by lewisdaly** [comment]
I'm looking into some of the errors reported in the `vulnerability-check` step for the central-ledger, and I can't determine if they are related to the above issue.

For example: https://circleci.com/gh/mojaloop/central-ledger/7550

```
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits 522ms
npm timing audit body Completed in 0ms
npm verb exit [ 0, true ]
npm timing npm Completed in 1105ms
npm info ok 
npm verb lifecycle @mojaloop/central-ledger@7.4.4~audit:check: unsafe-perm in lifecycle true
npm verb lifecycle @mojaloop/central-ledger@7.4.4~audit:check: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/circleci/project/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle @mojaloop/central-ledger@7.4.4~audit:check: CWD: /home/circleci/project
npm info lifecycle @mojaloop/central-ledger@7.4.4~audit:check: Failed to exec audit:check script
npm verb stack Error: @mojaloop/central-ledger@7.4.4 audit:check: `SHELL=sh check-audit "--json"`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:189:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:189:13)
npm verb stack     at maybeClose (internal/child_process.js:970:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```


Unfortunately, for builds such as this, CircleCI is not showing any build artifacts (despite logging that it has found them)

**Comment by lewisdaly** [comment]
What's more, the original error was exiting with a code `2`, whereas the above is existing with `1`, so this leads me to think this isn't the original error.

**Comment by lewisdaly** [comment]
So we haven't really been able to reproduce this recently. 

@mdebarros have you seen this issue elsewhere in some of the other repos recently?

**Comment by lewisdaly** [comment]
Could not reproduce. I suspect it was a temporary issue with npm. We can always reopen if we see it again.
