### ISSUE TITLE
Unable to upgrade dependencies in Central-Ledger

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#963]
**Summary**:
Central-Ledger fails tests when upgrading the following dependencies:
- Bump @mojaloop/central-services-stream from 6.2.2 to 7.4.0  dependencies

It would seem that the stubs for the stream lib are not functioning with 7.4.0 of the central-service-stream as we see the following error when running unit tests:
```
# Transfer handler prepare should persist transfer to database when messages is an array
2019-09-05T11:58:28.270Z - info: CreateHandler::connect - creating Consumer for topics: [topic-test]
2019-09-05T11:58:58.337Z - error: Consumer::onError()[topics='topic-test'] - Error: Local: Broker transport failure)
2019-09-05T11:58:58.337Z - error: Consumer::onError()[topics='topic-test'] - Error: Local: All broker connections are down)
2019-09-05T11:58:58.441Z - error: Consumer::onError()[topics='topic-test'] - Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/Users/mdebarros/Documents/ModusDocs/Projects/MojaLoop/git/fork/central-ledger/node_modules/node-rdkafka/lib/error.js:334:10)
    at /Users/mdebarros/Documents/ModusDocs/Projects/MojaLoop/git/fork/central-ledger/node_modules/node-rdkafka/lib/client.js:339:28)
2019-09-05T11:58:58.443Z - warn: CreateHandler::connect - error: Error: broker transport failure
ok 738 should be equal
# Transfer handler prepare should persist transfer to database when messages is an array - consumer throws error
2019-09-05T11:58:58.476Z - info: CreateHandler::connect - creating Consumer for topics: [topic-test]
```

**Severity**:
Low

**Priority**:
Medium

**Expected Behavior**
All tests should pass with the latest dependencies.

**Steps to Reproduce**
  1. Clear out the `reject` list in the [.ncurc.json](https://github.com/mojaloop/central-ledger/blob/master/.ncurc.json) file.
  2. Run `npm run dep:update`
  3. Run `npm run test`

**Specifications**
  - Component (if known): central-ledger
  - Version: v7.4.*
  - Platform: n/a
  - Subsystem: testing
  - Type of testing: manual
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: Low
- Priority when opened: Medium

**Comment by ggrg** [comment]
Just checked - this issue has been resolved.
