### ISSUE TITLE
Failure in CI build when 'gitbook-plugin-uml' version higher than '1.0.1' is used

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#995]
**Summary**:
In `documentation` repo, when the version of `gitbook-plugin-uml` dependency in `package.json` is upgraded beyond `1.0.1`, CI build fails with the following error:

```
#!/bin/sh -eo pipefail
npm install
> phantomjs-prebuilt@2.1.16 install /home/circleci/project/node_modules/phantomjs-prebuilt
> node install.js
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [] 0%
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /home/circleci/project/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1569330299802/phantomjs-2.1.1-linux-x86_64 -> /home/circleci/project/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/circleci/project/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
> node-plantuml@0.8.1 postinstall /home/circleci/project/node_modules/node-plantuml
> node scripts/get-vizjs.js
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-plantuml@0.8.1 postinstall: `node scripts/get-vizjs.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-plantuml@0.8.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-24T13_05_05_848Z-debug.log
Exited with code 1
```
**Severity**: Medium

**Priority**: Low

**Expected Behavior**
When the version of any dependency is upgraded and local builds and tests pass, CI build should also pass.

**Steps to Reproduce**
  1. Fork and clone the (documentation)[https://github.com/mojaloop/documentation] repo
  2. Make a branch
  2. Upgrade the version for `gitbook-plugin-uml` in `package.json`
  3. Run `npm install`
  4. Create a PR on the branch for CI build to kick in.

**Specifications**
  - Component (if known): documentation
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @oderayi 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Low

**Comment by elnyry-sam-k** [comment]
This may not be worth fixing anymore as we're moving to vuepress (from gitbooks).. 

Please reopen if that is not the case..
